//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.Matriculas = new HashSet<Matricula>();
        }

        public Aluno(string n)
        {
            this.Matriculas = new HashSet<Matricula>();
        }

        public int alu_cod { get; set; }
        public string alu_nome { get; set; }
        public string alu_RA { get; set; }
        public string alu_telefone { get; set; }
        public Nullable<int> disc_cod { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matricula> Matriculas { get; set; }
    }
}
