//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int mat_cod { get; set; }
        public Nullable<int> alu_cod { get; set; }
        public Nullable<int> disc_cod { get; set; }
        public Nullable<decimal> mat_nota1 { get; set; }
        public Nullable<decimal> mat_nota2 { get; set; }
        public Nullable<decimal> mat_media { get; set; }
        public string mat_status { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Disciplina Disciplina { get; set; }
    }
}
